### ISSUE TITLE
Locks dont load

### ISSUE THREAD

**Issue by riptidemamba** [Eggs-D-Studios/wos-issues#331] opened 2024-09-01 01:11 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Sometimes when joining the game the Lock UI (C) does not show anything but a blank frame (i dont have a ss but literally just the backdrop) and takes around 1-5min to load. During this time you cannot interact with ANY of your own stuff it's just very annoying

### How can we reproduce this bug?

1. Join the game (preferably high ping server)
2. Boom

### Frequency

I can't make it happen consistently

**Comment by Hexcede** [comment] 2024-09-01 09:01
Duplicate of #322

**Closed by Hexcede** 2024-09-01 09:01 UTC
Labels: bug, duplicate, confirmed, production
