### ISSUE TITLE
Servos don't properly weld when loaded in with a model

### ISSUE THREAD

**Issue by Martynaspukis** [Eggs-D-Studios/wos-issues#519] opened 2024-10-24 14:22 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Instead of saving the hinge weld and being able to spin, the servo now just welds it and it can't spin, additionally, when using ctrl + lock on this it highlights the entire build but doesn't lock anything beyond the first servo

### How can we reproduce this bug?

Build a servo, on top of it something, a servo on top of something, and something on top of the second servo and save to model
Load this model into game
Try to lock all
Fail
Try to make it spin
Fail

### Frequency

Always

**Comment by Martynaspukis** [comment] 2024-10-24 14:23
![image](https://github.com/user-attachments/assets/e83ddee1-1718-435f-a1a7-a8d28ba56c59)

**Comment by NameTemplate** [comment] 2024-10-25 02:53
> additionally, when using ctrl + lock on this it highlights the entire build but doesn't lock anything beyond the first servo
this is already known i think

**Comment by RiskoZoSlovenska** [comment] 2024-10-25 15:42
I'm pretty sure this is a duplicate of https://github.com/Eggs-D-Studios/wos-issues/issues/362 and https://github.com/Eggs-D-Studios/wos-issues/issues/485 respectively.

**Comment by Martynaspukis** [comment] 2024-10-27 07:23
> I'm pretty sure this is a duplicate of #362 and #485 respectively.

#362 mentions the spinning bug is fixed

#485 doesn't mention servos at all

**Comment by NameTemplate** [comment] 2024-10-28 00:10
> > I'm pretty sure this is a duplicate of #362 and #485 respectively.
> 
> #362 mentions the spinning bug is fixed
> 
> #485 doesn't mention servos at all

#485 i mentioned servos as a comment

**Comment by NameTemplate** [comment] 2024-10-28 12:25
I just tested this and it works fine for me? unless this only happens when two servos?

**Comment by NameTemplate** [comment] 2024-10-28 12:28
> I just tested this and it works fine for me? unless this only happens when two servos?

tested it with two
works as well
did you build the model in game or with mbtools? (or mbee)

test model:
![image](https://github.com/user-attachments/assets/b3cc2469-3d94-4204-81b6-3fbba0ccbf93)

**Comment by Martynaspukis** [comment] 2024-10-31 14:08
> test model: ![image](https://private-user-images.githubusercontent.com/134684936/380712788-b3cc2469-3d94-4204-81b6-3fbba0ccbf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODM4MjksIm5iZiI6MTczMDM4MzUyOSwicGF0aCI6Ii8xMzQ2ODQ5MzYvMzgwNzEyNzg4LWIzY2MyNDY5LTNkOTQtNDIwNC04MWI2LTNmYmJhMGNjYmY5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNDA1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDY1NjFhOTJiODA4NTU3YjIyMDk3ZjZkZWEzMTBjMGZhOTFkMzQ1ZGM1MDM4M2ZkOGQzYjcyYTYxYTI5MWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NYMTUReMppvTNF0d2uLBdVtBcweTgWIh40rz1DajQss)


I built my build in game, then saved with model system, then if you load it doesn't work. Did you build yours with studio???

**Comment by NameTemplate** [comment] 2024-10-31 14:32
nope
built it in game

**Comment by Martynaspukis** [comment] 2024-10-31 19:33
Basically, this works IF you build it simply, but if you save it and then load it in again, then it breaks

**Comment by NameTemplate** [comment] 2024-11-01 12:26
> Author

thats what i did
i built it, saved it, and loaded it again
nothing happened

**Comment by dogranger1** [comment] 2024-11-20 23:18
![image](https://github.com/user-attachments/assets/11e577f4-9c54-498d-8056-73021d3ae5ec)

https://github.com/user-attachments/assets/3084884b-8c9f-4a3d-8e56-f7c9cbe5f2c1

perhaps this happens because one of the other parts on the servo slightly part shifted and welded itself to the part. What's interesting about this is group locking works (which is unexpected)

https://github.com/user-attachments/assets/5e9fbde9-829f-4dcb-a549-95479d266430

model builder code:
`{"m":null,"t":"buffer","zbase64":"KLUv/WCDA0UNAMZQPjhQjdIB0JnZJtOkZ2ahRFXVOLDwmz9+DFx5NIPlE6BiyUFVMPCRYjvAi7ZyPGlkhLtmdzey9yYyBSwAKgAyAD9HI/mz3IG9bZtGxoam+U3524YhAhJyn+Wb8p/ldzp+reTvjPyn/jfxt8UflP7/rvtQaYQ9XWHXnGSn/7NBoaCyVBn7P4Q/9iF9QP3H1/MPUv2/4ekDmEgHLCqjwKVS1q1Qft6LCJM8+IOD0yh3cxDGIk/lUuTPrsMcLnl0XEjU4Yu+ZdFKAEA22oyVHAkaUemEeHCYXC3f2zAsNNVcLd/VkguNKjomIBwYYNdO02n+NtqMrQSWpcoKE1uoUa106khT2VgD4AIhIs4DEsAAurCnCBFIQRJIQAqk9j8Dzo5p8hKpuH94uWFLsn7zCp5xDlY4yaHpgErf30HdCM4OKwlW+p7XImHJHhmAxrJq9eeF5VOTLF0Tjo7PBIAULm22YV00TKfprIwBRt+xue4tI2fyviiJpziUhGue+ht0yrmKRalSIr4ZNtn7gvYzbdNQUd+l0k7WRyvWbLvytF44gvqvIaaauAo="}`

**Comment by NameTemplate** [comment] 2024-11-21 10:15
> ![image](https://github.com/user-attachments/assets/11e577f4-9c54-498d-8056-73021d3ae5ec)
> 
> https://github.com/user-attachments/assets/3084884b-8c9f-4a3d-8e56-f7c9cbe5f2c1
> 
> perhaps this happened to you because one of the other parts on the servo slightly part shifted and welded itself to the part (this could be why reloading the model results in this bug). What's interesting about this is group locking works (which is unexpected)
> 
> https://github.com/user-attachments/assets/5e9fbde9-829f-4dcb-a549-95479d266430
> 
> model builder code:
> ```{"m":null,"t":"buffer","zbase64":"KLUv/WCDA0UNAMZQPjhQjdIB0JnZJtOkZ2ahRFXVOLDwmz9+DFx5NIPlE6BiyUFVMPCRYjvAi7ZyPGlkhLtmdzey9yYyBSwAKgAyAD9HI/mz3IG9bZtGxoam+U3524YhAhJyn+Wb8p/ldzp+reTvjPyn/jfxt8UflP7/rvtQaYQ9XWHXnGSn/7NBoaCyVBn7P4Q/9iF9QP3H1/MPUv2/4ekDmEgHLCqjwKVS1q1Qft6LCJM8+IOD0yh3cxDGIk/lUuTPrsMcLnl0XEjU4Yu+ZdFKAEA22oyVHAkaUemEeHCYXC3f2zAsNNVcLd/VkguNKjomIBwYYNdO02n+NtqMrQSWpcoKE1uoUa106khT2VgD4AIhIs4DEsAAurCnCBFIQRJIQAqk9j8Dzo5p8hKpuH94uWFLsn7zCp5xDlY4yaHpgErf30HdCM4OKwlW+p7XImHJHhmAxrJq9eeF5VOTLF0Tjo7PBIAULm22YV00TKfprIwBRt+xue4tI2fyviiJpziUhGue+ht0yrmKRalSIr4ZNtn7gvYzbdNQUd+l0k7WRyvWbLvytF44gvqvIaaauAo="}```
> 

group locking worked because hexcede fixed it recently

**Comment by Hexcede** [comment] 2024-11-22 18:37
I believe some changes relatively recently likely fixed this incidentally, there are still some hinge related bugs for sure though

**Closed by Hexcede** 2024-11-22 18:37 UTC
Labels: bug, confirmed, production
