### ISSUE TITLE
Region's strange loading performance

### ISSUE THREAD

**Issue by 1enu** [Eggs-D-Studios/wos-issues#447] opened 2024-09-28 13:59 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Game loads, but client ping keeps rising and seem to never recover on the region's first load. Leaving and rejoining as soon as your character loads(not "waiting for roblox", the phase where your GUI shows up) makes the process faster and faster until it is almost instant.

This is a generalized version of #436 with more testing and observation included.

### How can we reproduce this bug?

Join an region that hasn't been loaded for some time(i don't know what time exactly, just wait a long time)
Notes: 
- The planet has 4 microcontrollers but all of them are manually activated(no StartOnSpawn) and have at most 10 lines of code.
- No reactors(just in case)

General loading sequence(as seen from debug console):

- Loading 3d skybox(at this point it shows "Waiting for roblox")
- ValueHandler and Animations loads(your character spawns, but your buttons cannot be pressed)
- Loading cmdr/Control initialized/others(once this shows up all guis/tools are active)

So overall, there are two times:

- **Time to ValueHandler** (your character spawns)
- **Time to control** (everything is loaded)

## First load

![RobloxScreenShot20240927_163025847](https://github.com/user-attachments/assets/fead5e76-8cbf-4f96-8133-5a8a4f359aff)

Time to ValueHandler: `~2 minutes`
Time to control: `Did not finish`

I waited around 30 minutes as shown by the OST time stamps. At that point my ping was 17 million ms. What is interesting is that the power cell still updates every 1-2 seconds even though my ping was that high.

## Second load

![image](https://github.com/user-attachments/assets/7fbd0190-7307-4fbd-92e6-de0859578899)

Time to ValueHandler: `17 seconds`
Time to control: `~2.5 minutes`

Took around a minute to rejoin, but it was most definitely better.

## Third load

![image](https://github.com/user-attachments/assets/84e95240-beac-4f78-b57b-5c502cb4d95f)

Time to ValueHandler: `3 seconds`
Time to control: `less than 1 second`

This is what should be always happening.

### Frequency

Most of the time

**Comment by Hexcede** [comment] 2024-10-01 13:17
Duplicate of #436

**Closed by Hexcede** 2024-10-01 13:17 UTC
Labels: bug, duplicate, production
