### ISSUE TITLE
Spawning way above the atmospheric line

### ISSUE THREAD

**Issue by GooberGoonie** [Eggs-D-Studios/wos-issues#294] opened 2024-08-27 17:57 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I abnormally spawn extremely high up when entering any region making it so i cant enter planets and it takes me a while to get anywhere, practically softlocking me
![fart](https://github.com/user-attachments/assets/c94dffc2-acc0-4e40-af60-9cfc2f9a4cce)

### How can we reproduce this bug?

I dont understand how this even happened and was not able to fix or reproduce this

### Frequency

Always

**Comment by khaopong23TH4** [comment] 2024-08-28 06:53
This is unplayable. The only thing I could do is stay in my own planet.

**Comment by Hexcede** [comment] 2024-09-01 09:19
Duplicate of #183

**Closed by Hexcede** 2024-09-01 09:19 UTC
Labels: bug, duplicate, production
