### ISSUE TITLE
Cant Enter Planets Because Of Tp

### ISSUE THREAD

**Issue by jjboy17** [Eggs-D-Studios/wos-issues#300] opened 2024-08-28 02:01 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Staging)

### What happened? What did you expect to happen?

When I enter a planet I get tped back to the outerspace of the planet due to spawning too high I have tried going to other planets and it has done nothing.

### How can we reproduce this bug?

 1. Warp to a planet.
 2. Fly into it.
 3. It will teleport you back to the outside layer.

### Frequency

Always

**Comment by cat-microwave** [comment] 2024-08-28 02:17
we are also having the same problem. Heres a screen recording if that helps anything
 https://drive.google.com/file/d/1FhjKq-fkAncn1hvrgKu_j-QGzs2q1iFH/view?usp=sharing

**Comment by Joe-Derp** [comment] 2024-08-29 04:59
Duplicate of #183 ?

**Comment by Hexcede** [comment] 2024-09-01 09:18
Duplicate of #183

**Closed by Hexcede** 2024-09-01 09:18 UTC
Labels: bug, duplicate, staging
