### ISSUE TITLE
`Color3` and `BrickColor` properties always return `nil`

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#516] opened 2024-10-24 05:37 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

The following code:
```lua
local label = Instance.new("TextLabel")
label.BorderColor3 = Color3.new(1, 1, 1)
print(label.BorderColor3)
```
prints:
```
nil
```
whereas the expected output would be:
```
1, 1, 1
```
Note that the text label does have its `BorderColor3` set to the correct color; it's just reading the color that fails.

I am not sure if this is related to https://github.com/Eggs-D-Studios/wos-issues/issues/514; both bugs concern color values, but getting e.g. the `Font` property here works whereas in the referenced bug it does not.

### How can we reproduce this bug?

See above.

### Frequency

Always

**Comment by Hexcede** [comment] 2024-11-02 22:07
Duplicate of #514

**Closed** 2024-11-02 22:06 UTC
Labels: bug, duplicate, confirmed, production, pending
