### ISSUE TITLE
Ship spawn to high on planet Causes instant planet escapes

### ISSUE THREAD

**Issue by bladtax** [Eggs-D-Studios/wos-issues#312] opened 2024-08-29 01:59 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

on this planet me and my friend are base at its spawning the ships to high up and its making us get instantly warped off planet

if you need coords u can dm me - bladtax

### How can we reproduce this bug?

 1. Warp to space.
 2. Warp back to the planet.
 3. instantly teleported off

### Frequency

Always

**Comment by Joe-Derp** [comment] 2024-08-29 04:59
Duplicate of #183 ?

**Comment by Hexcede** [comment] 2024-09-01 09:17
Duplicate of #183

**Closed by Hexcede** 2024-09-01 09:17 UTC
Labels: bug, duplicate, confirmed, production
