### ISSUE TITLE
manualy attached parts gets crazy partshift after warp

### ISSUE THREAD

**Issue by ikwsgbygikwsg** [Eggs-D-Studios/wos-issues#445] opened 2024-09-27 14:27 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

when attaching parts using hammer tool and warping afterwards the parts that got placed by hammer tool gets partshifted

### How can we reproduce this bug?

https://github.com/user-attachments/assets/ea99caef-f9bb-4972-b868-4374ce188d47

### Frequency

Always

**Comment by Codewireweaver** [comment] 2024-09-30 21:24
I lost alot of ships to this bug hexcede pls fix

**Comment by Hexcede** [comment] 2024-10-01 13:22
Duplicate of #420

**Closed by Hexcede** 2024-10-01 13:22 UTC
Labels: bug, duplicate, production
