### ISSUE TITLE
StudAligner works wierd

### ISSUE THREAD

**Issue by zumroom** [Eggs-D-Studios/wos-issues#325] opened 2024-08-31 10:44 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

My ship sank underground due to the stud aligner, when I activate it it turns towards a certain direction with only scripts of this buggy game knows what. The "StudAligner" does not work the same way as before, instead of always turning to the north, it turns in an almost unpredictable direction. This cube definitely has a pattern of how to turn depending on how the parts on it are turned.

### How can we reproduce this bug?

1. Place "StudAligner" 
2. Place smething on "StudAligner" and turn it by "T" key
3. Activate "StudAligner".

### Frequency

Always

**Comment by AluminumAlman** [comment] 2024-08-31 16:49
May be similar to #276

**Comment by Hexcede** [comment] 2024-09-01 08:57
Duplicate of #276

**Closed** 2024-09-01 08:57 UTC
Labels: bug, duplicate, confirmed, production
