### ISSUE TITLE
Model Lock Spawn

### ISSUE THREAD

**Issue by macaylej** [Eggs-D-Studios/wos-issues#354] opened 2024-09-05 12:07 UTC
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

Once i think about the problem of people can group saving the unlocked models, They have potential that they can steal ships from other players once they spawned on the test zone

This could lead massive Stealing problem that they might even steal a week built ships and keeping it in their studio

### What do you propose? What should change, or what should be added?

Have a Setting that Lock Models before spawning

**Comment by Hexcede** [comment] 2024-09-05 12:19
Duplicate of #303

**Closed by Hexcede** 2024-09-05 12:19 UTC
Labels: duplicate, enhancement, production
