### ISSUE TITLE
Microcontroller Configuration Issue

### ISSUE THREAD

**Issue by h1guys329** [Eggs-D-Studios/wos-issues#318] opened 2024-08-29 19:52 UTC
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

My microcontroller wont update signs with :Configure
This is what my code looks like.

local Port = GetPort(1)
local Sign = GetPartFromPort(2, 'Sign')
Counter = 0

Port:Connect("Triggered", function()
Counter = Counter + 1
print(Counter)
Sign:Configure({SignText = Counter})
end)

It prints an elevating number everytime i send a trigger signal through the port, and it puts the number in the signs configuration, but doesnt apply it to the sign.

### How can we reproduce this bug?

1. Put the code in the microcontroller.
2. Send a trigger signal through port 1 while having a sign attached to port 2.
3. Open the config on the sign.

### Frequency

Always

**Comment by Hexcede** [comment] 2024-09-01 09:08
Duplicate of #250

**Closed by Hexcede** 2024-09-01 09:08 UTC
Labels: bug, duplicate, confirmed, production
